version: '3.8'
services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cuf49ljtq21c73evpf0g-a.oregon-postgres.render.com:5432/s19d4_postgresql?sslmode=require
      - SPRING_DATASOURCE_USERNAME=s19d4_postgresql_user
      - SPRING_DATASOURCE_PASSWORD=UhtHNUO2nRia6UzsOvOYSuKzd6MYd6Ie
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=fsweb